import type { ContractDraft } from "@/lib/contracts/types";

export const seedContracts: ContractDraft[] = [
  {
    title: "EXL awarded F&A BPO contract for European retail operations",
    body: "EXL will provide order-to-cash and accounts payable services from India and Poland for a major European retailer, targeting a 20% cost reduction over 36 months.",
    informationType: "Contracts",
    serviceLine: "F&A",
    industry: "Retail",
    serviceProvider: "EXL",
    geography: "Europe",
    countrySigned: "India",
    deliveryLocation: "India; Poland",
    clientName: "Confidential Retail Client",
    contractStartDate: "2014-03-04",
    contractLengthMonths: 36,
    contractEndEstimated: true,
    tcvUsd: 20000000,
    tcvEstimated: true,
    contractType: "New Contract",
    platform: "Workday",
    saasPlatform: true,
    source: "Seed from tracker blueprint",
    aiConfidence: 0.84,
  },
  {
    title: "Cognizant signs application modernization deal with UK telecom",
    body: "Cognizant was selected for cloud migration and app support modernization for a UK telecom, with mixed onshore and offshore delivery.",
    informationType: "Contracts",
    serviceLine: "Application Services",
    industry: "Telecom",
    serviceProvider: "Cognizant",
    geography: "United Kingdom",
    countrySigned: "United Kingdom",
    deliveryLocation: "United Kingdom; India",
    clientName: "UK Telecom Operator",
    contractStartDate: "2015-06-24",
    contractLengthMonths: 48,
    contractEndEstimated: true,
    tcvUsd: 32000000,
    tcvEstimated: true,
    contractType: "Renewal",
    platform: "AWS",
    saasPlatform: false,
    source: "Seed from tracker blueprint",
    aiConfidence: 0.82,
  },
  {
    title: "Accenture and healthcare payer announce analytics partnership",
    body: "Accenture launched a claims analytics and automation initiative with a North American healthcare payer.",
    informationType: "Partnerships",
    serviceLine: "Analytics",
    industry: "Healthcare",
    serviceProvider: "Accenture",
    geography: "North America",
    countrySigned: "United States",
    deliveryLocation: "United States; Costa Rica",
    clientName: "Healthcare Payer",
    contractStartDate: "2016-01-18",
    contractLengthMonths: 24,
    contractEndEstimated: true,
    tcvUsd: 12000000,
    tcvEstimated: true,
    contractType: "Strategic Partnership",
    platform: "Snowflake",
    saasPlatform: true,
    source: "Seed from tracker blueprint",
    aiConfidence: 0.8,
  },
  {
    title: "TCS acquires niche cybersecurity automation firm",
    body: "TCS acquired a cybersecurity automation provider to strengthen managed security offerings in BFSI and public sector.",
    informationType: "M&A",
    serviceLine: "Cybersecurity",
    industry: "BFSI",
    serviceProvider: "TCS",
    geography: "Global",
    countrySigned: "India",
    deliveryLocation: "India; United States",
    clientName: "N/A",
    contractStartDate: "2015-12-13",
    contractLengthMonths: 12,
    contractEndEstimated: true,
    tcvUsd: 45000000,
    tcvEstimated: true,
    contractType: "Acquisition",
    platform: "N/A",
    saasPlatform: false,
    source: "Seed from tracker blueprint",
    aiConfidence: 0.86,
  },
  {
    title: "Infosys launches HR SaaS offering for enterprise workforce ops",
    body: "Infosys introduced an HR-as-a-Service package combining payroll, talent services and Workday advisory for multinational clients.",
    informationType: "New Offerings",
    serviceLine: "HR Services",
    industry: "Cross-Industry",
    serviceProvider: "Infosys",
    geography: "Global",
    countrySigned: "India",
    deliveryLocation: "India; Philippines",
    clientName: "Multi-client",
    contractStartDate: "2016-02-01",
    contractLengthMonths: 18,
    contractEndEstimated: true,
    tcvUsd: 9000000,
    tcvEstimated: true,
    contractType: "New Offering",
    platform: "Workday",
    saasPlatform: true,
    source: "Seed from tracker blueprint",
    aiConfidence: 0.78,
  },
  {
    title: "TCS reports strong annual financial results driven by managed services growth",
    body: "TCS announced annual revenue growth supported by cloud, application services, and business process services demand across North America and Europe.",
    informationType: "Financial Results",
    serviceLine: "Application Services",
    industry: "Cross-Industry",
    serviceProvider: "TCS",
    geography: "Global",
    countrySigned: "India",
    deliveryLocation: "Global",
    clientName: "N/A",
    contractStartDate: "2016-04-15",
    contractLengthMonths: 12,
    contractEndEstimated: true,
    tcvUsd: 0,
    tcvEstimated: true,
    contractType: "Financial Results",
    platform: "Not Specified",
    saasPlatform: false,
    source: "Seed from tracker blueprint",
    aiConfidence: 0.79,
  },
];

export const prepopulateSnippets: string[] = [
  "EXL was awarded a 3-year finance and accounting outsourcing contract with a European retailer. The deal is estimated at $20m and includes order-to-cash services delivered from India and Poland.",
  "Wipro signed a five-year infrastructure management agreement with a US insurance client, valued at approximately $35 million, with primary delivery from Bangalore and Dallas.",
  "Capgemini and a global bank announced a strategic partnership to deploy cloud-native risk analytics across North America and Europe.",
  "Genpact launched a new procurement-as-a-service offering for manufacturing clients, built on Coupa and SAP Ariba integrations.",
  "HCLTech acquired a cybersecurity monitoring startup to accelerate managed detection and response capabilities for enterprise clients.",
  "Cognizant secured a 24-month customer operations contract in telecom with estimated TCV of $8m, delivery from the Philippines and India.",
  "Infosys reported quarterly financial results with revenue growth in digital and business process services across North America and Europe.",
];
